#app
spring.application.name=tejiendo-arte

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tejiendo_arte
spring.datasource.username=root
spring.datasource.password=eosiokiz5

#jdbc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true